### ISSUE TITLE
Don't need to ask for consent to cache files

### ISSUE THREAD

**Issue by hadley** [e-kotov/rJavaEnv#45]
I don't think it's necessary to ask permission to use a cache directory (and I have quite a few packages on CRAN that assume this, so it seems like CRAN is ok with it too). I do think you need to ask permission to write to `~/.Rprofile` and `.Rprofile`.

**Comment by e-kotov** [comment]
I can try submitting without this) Depends whether CRAN considers cache as [user's home filespace](https://cran.r-project.org/web/packages/policies.html#:~:text=user%E2%80%99s%20home%20filespace) 😉 . Technically, it is in users home folder.

**Comment by e-kotov** [comment]
Closed by #46  #47 . You do not, but in the end I decided not to ask only for `use_java()`, as this is for pro users and relatively safe. For all other functions there is still consent, like with `renv`.
